services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --listen=*:8000 Sportfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Sportfolio.settings
      - key: SECRET_KEY
        value: 'django-insecure-l3)&4@ja7%!47!nc4r48)#h02v@#x-y42f(zy_%g)#nt2751ci'
      - key: ALLOWED_HOSTS
        value: "*"
